### ISSUE TITLE
[BUG] Restart of first cluster member can lead to quorum loss while scaling up a non-HA etcd cluster.

### ISSUE THREAD

**Issue by ishan16696** [gardener/etcd-backup-restore#646]
**Describe the bug:**
It has been observed in between of scaling up(`1->3 replicas`) a non-HA etcd cluster to HA etcd cluster if etcd's first member pod restarted(due to any reason) then this restart of etcd first cluster member in between of scaling-up a cluster might lead to permanent quorum loss when second etcd cluster joined the cluster successfully but third etcd cluster member didn't join the cluster yet or didn’t started yet.
So, now first and third member both are down at the same time which leads to permanent quorum loss.

[etcd CR status](https://storage.googleapis.com/gardener-prow/logs/ci-gardener-e2e-kind-ha-multi-zone-upgrade/1678703053483544576/artifacts/etcds.yaml):
```
  status:
    clusterSize: 1
    conditions:
    - lastTransitionTime: "2023-07-11T10:16:09Z"
      lastUpdateTime: "2023-07-11T11:12:40Z"
      message: At least one member is not ready
      reason: NotAllMembersReady
      status: "False"
      type: AllMembersReady
    - lastTransitionTime: "2023-07-11T10:29:39Z"
      lastUpdateTime: "2023-07-11T11:12:40Z"
      message: Stale snapshot leases. Not renewed in a long time
      reason: BackupFailed
      status: "False"
      type: BackupReady
    - lastTransitionTime: "2023-07-11T10:16:09Z"
      lastUpdateTime: "2023-07-11T11:12:40Z"
      message: The majority of ETCD members is not ready
      reason: QuorumLost
      status: "False"
      type: Ready
    currentReplicas: 1
    etcd:
      apiVersion: apps/v1
      kind: StatefulSet
      name: etcd-main
    members:
    - id: bd585ad8a06f8cfb
      lastTransitionTime: "2023-07-11T10:16:09Z"
      name: etcd-main-0
      reason: UnknownGracePeriodExceeded
      role: Leader
      status: NotReady
    observedGeneration: 1
    ready: false
    replicas: 1
    serviceName: etcd-main-client
    updatedReplicas: 2
```

**Expected behaviour:**
We can't control the restart of etcd pod as restart of etcd member pod could be cause by some infra issue or some after effect but we can avoid this permanent quorum loss from happening.

**Logs:**
`backup-restore` logs of `etcd-main-0` pod:
```
2023-07-11T11:10:59.231764125Z stderr F time="2023-07-11T11:10:59Z" level=error msg="Failed to connect to etcd KV client: context deadline exceeded" actor=member-add
2023-07-11T11:10:59.231770196Z stderr F time="2023-07-11T11:10:59Z" level=error msg="unable to check presence of member in cluster: context deadline exceeded" actor=member-add
2023-07-11T11:10:59.235463591Z stderr F time="2023-07-11T11:10:59Z" level=info msg="Etcd cluster scale-up is detected" actor=initializer
.
.
.
2023-07-11T11:12:33.848388409Z stderr F time="2023-07-11T11:12:33Z" level=fatal msg="unable to add a learner in a cluster: error while adding member as a learner: context deadline exceeded" actor=initializer
```

**Environment (please complete the following information):**
 - Etcd version/commit ID :
 - Etcd-backup-restore version/commit ID:
 - Cloud Provider [All/AWS/GCS/ABS/Swift/OSS]: 

**Anything else we need to know?**:
Failed Prow jobs: 
1. https://gcsweb.gardener.cloud/gcs/gardener-prow/logs/ci-gardener-e2e-kind-ha-multi-zone-upgrade/1678703053483544576/artifacts/
2. https://gcsweb.gardener.cloud/gcs/gardener-prow/logs/ci-gardener-e2e-kind-ha-single-zone-upgrade-release-v1-74/1679656031631708160/artifacts/
3. https://gcsweb.gardener.cloud/gcs/gardener-prow/logs/ci-gardener-e2e-kind-ha-single-zone-upgrade-release-v1-75/1679699568997961728/artifacts/
