### ISSUE TITLE
[BUG] Full Snapshot lease update should be retried and should not wait for the next full snapshot trigger

### ISSUE THREAD

**Issue by unmarshall** [gardener/etcd-backup-restore#678]
**Describe the bug:**
It is possible that after taking a full snapshot, the full-snapshot-lease update fails. Reasons for failure can be many (KAPI not available, KAPI not reachable due to network issues, connections are timing out etc.). 
Currently we try and update the snapshot lease just once. See [here](https://github.com/gardener/etcd-backup-restore/blob/master/pkg/snapshot/snapshotter/snapshotter.go#L639-L643). 

This is not an issue with the delta snapshot, as delta snapshots get taken every 5 mins, so a re-attempt is automatically done to update the delta-snapshot-lease. Since taking full-snapshots is expensive, today we do this once in 24 hrs. So the next attempt to update the full-snapshot-lease will be after 24 hrs.

This has a side effect that the snapshot ready condition maintained by etcd-druid on the etcd resource status continues to state that the status is unknown:

Example:
```yaml
- lastTransitionTime: "2023-11-08T21:09:17Z"
    lastUpdateTime: "2023-11-09T03:44:23Z"
    message: Cannot determine etcd backup status
    reason: Unknown
    status: Unknown
    type: BackupReady
```
Consequence of this that gardener reports that not all control plane components are healthy. This was recently observed again in Live#3989.

**Expected behavior:**
Re-attempts should be made to update the full-snapshot-lease.

**How To Reproduce (as minimally and precisely as possible):**
One way to reproduce this to scale down KAPI and trigger a full snapshot.
