### ISSUE TITLE
Simplify etcd sidecar setup

### ISSUE THREAD

**Issue by mvladev** [gardener/etcd-backup-restore#78]
At the moment the `etcdbrctl` is deployed as a side-car container: https://github.com/gardener/etcd-backup-restore/blob/3cbb0bada663641c21184641c09737523be20337/example/etcd-statefulset-aws.yaml#L91-L102

and forcing the client (the main container) to execute several rest calls to the running server: https://github.com/gardener/etcd-backup-restore/blob/3cbb0bada663641c21184641c09737523be20337/example/etcd-statefulset-aws.yaml#L25-L42 until finally, starting the etcd. This entire setup can be simplified greatly by having `etcdbrctl` be the one starting etcd as it knows exactly when to start etcd or even stop it on demand if needed. As an example:

```yaml
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: etcd-aws
spec:
  selector:
    matchLabels:
      app: etcd-aws
  serviceName: "etcd-aws"
  replicas: 1
  template:
    metadata:
      labels:
        app: etcd-aws 
    spec:
      containers:
      - name: backup
        command:
        - etcdbrctl
        - run # or some other name
        - --schedule=*/5 * * * *
        - --max-backups=5
        - --data-dir=/var/etcd/data
        - --insecure-transport=true
        - --storage-provider=S3
        - --delta-snapshot-period-seconds=10
        - --garbage-collection-period-seconds=60
        - -- # end of parameter list
        - etcd
        - --data-dir=/var/etcd/data
        - --name=etcd 
        - --advertise-client-urls=http://0.0.0.0:2379 
        - --listen-client-urls=http://0.0.0.0:2379 
        - --initial-cluster-state=new 
        - --initial-cluster-token=new
        image: eu.gcr.io/gardener-project/gardener/etcdbrctl:0.2.3
```

looks better and it in this case `etcdbrctl` does not need to start a rest api server and can directly work with etcd, putting it in charge of it, and any misbehaving clients don't break the workflow.
