### ISSUE TITLE
[Feature] Backup already existing etcd cluster

### ISSUE THREAD

**Issue by jurim76** [gardener/etcd-backup-restore#783]
Is it possible to use "etcdbrct snapshot" to backup already existing etcd cluster, using etcdbrctl pod's hostPath and hostNetwork?
etcdbrctl pod example manifest
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    owner_team: ops-devops
  name: etcd-backup
spec:
  imagePullSecrets:
    - name: regcred
  containers:
  - image: local.reg/etcd-backup:latest
    name: etcd-backup
    volumeMounts:
    - name: etcd-certs
      mountPath: /etc/kubernetes/pki/etcd
      readOnly: true
    - name: data
      mountPath: /data
  tolerations:
  - effect: NoSchedule
    operator: Exists
  hostNetwork: true
  volumes:
  - name: etcd-certs
    hostPath:
      path: /etc/kubernetes/pki/etcd
      type: DirectoryOrCreate
  - name: data
    emptyDir: {}
    ```
